# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
commands:
  setup-sccache:
    description: "Install sccache"
    steps:
      # - run: 
      #     name: "Install wget"
      #     command: apt-get update && apt-get install --yes libpq-dev wget
      - run:
          name: "install sccache"
          command: wget https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz && tar xzf sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz && chmod +x sccache-v0.2.15-x86_64-unknown-linux-musl/sccache
      - run:
          name: "set env"
          command: |
            echo 'export "RUSTC_WRAPPER"="sccache"' >> $BASH_ENV
            echo 'export "SCCACHE_CACHE_SIZE"="1G"' >> $BASH_ENV
            sccache-v0.2.15-x86_64-unknown-linux-musl/sccache --version
            alias sccache="sccache-v0.2.15-x86_64-unknown-linux-musl/sccache"
            sudo cp sccache-v0.2.15-x86_64-unknown-linux-musl/sccache /usr/local/bin
            sccache --version
  restore-sccache-cache:
    description: "Restore sccache"
    steps:
      - restore_cache:
          name: "Restore sccache cache"
          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
  save-sccache-cache:
    description: "save_cache"
    steps:
      - save_cache:
          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/rust:latest
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - setup-sccache
      - restore-sccache-cache
      - run:
          name: "build-wasm"
          command: "cargo build --bin desk-client --target wasm32-unknown-unknown --release --features web"
      - run:
          name: "wasm-bindgen"
          command: "./wasm-bindgen --out-dir public --target web target/wasm32-unknown-unknown/release/desk-client.wasm"
      - save-sccache-cache
      
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello